require 'securerandom'
require_relative 'reservoir/keycreator'
require_relative 'reservoir/timestamper'
require_relative 'reservoir/repository/in_memory_repository'
require_relative 'reservoir/repository/sequel_repository'
